# This workflow will perform a clean install of Node dependencies, and lint and compile the source code.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Lint and compile

# https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request
# By default, the workflow only runs when a pull_request's activity type is opened, synchronize, or reopened.
on: pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm ci
    - run: npm run lint
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm ci
    - run: npm run build
    
